receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: localhost:5000
    insecure: false

  otlphttp:
    endpoint: http://localhost:9000

  logging:
    loglevel: debug


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]
