receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

exporters:
  otlp:
    endpoint: 0.0.0.0:5000
    insecure: true
  otlphttp: # for additional setting see https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
    endpoint: <ebdpoint>
    insecure: true
  prometheus:
    endpoint: 0.0.0.0:9009

service:
  pipelines:
    metrics/demo:
      receivers: [otlp]
      exporters: [otlp, prometheus, otlphttp]
