receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

exporters:
  otlp:
    endpoint: 0.0.0.0:5000
    insecure: true

service:
  pipelines:
    metrics/demo:
      receivers: [otlp]
      exporters: [otlp]
