receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:30080

exporters:
  otlphttp: # for additional settings see https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter/otlphttpexporter
    endpoint: <endpoint> # point this to oltp http based endpoint
    insecure: true


service:
  pipelines:
    metrics/demo:
      receivers: [otlp]
      exporters: [otlphttp]
