receivers:
  otlp:
    protocols:
      grpc:

exporters:
  otlp:
    endpoint: localhost:5000
    insecure: false
    ca_file: /tmp/certs/ca.pem

  logging:
    loglevel: debug


service:
  pipelines:
    metrics/demo:
      receivers: [otlp]
      exporters: [logging, otlp]
